<a href="https://colab.research.google.com/github/un1u3/ml-labs/blob/main/Deep%20Learning/Pytorch/00_BasicsPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


#Core Pytorch Modules
| Module             | Purpose                               |
| ------------------ | ------------------------------------- |
| `torch`            | Tensors, math ops, core engine        |
| `torch.nn`         | Layers, models, activations, losses   |
| `torch.optim`      | Optimizers (SGD, Adam, etc.)          |
| `torch.utils.data` | Datasets and DataLoaders              |
| `torch.autograd`   | Automatic gradient computation        |
| `torchvision`      | Images, pretrained models, transforms |


What are Tensors
- Tensor is a specialied multi-dimensional arra designed for mathematical and computational efficiency

In [3]:
print(torch.__version__)

2.6.0+cu124


In [4]:
if torch.cuda.is_available():
  print("CUA",torch.cuda.get_device_name(0))
else:
  print("NO")

CUA Tesla T4


# creating a tensor


In [8]:
# using empty
a = torch.empty(2,3)
# make space for 2x3 mat

In [9]:
# check type
type(a)

torch.Tensor

In [10]:
# using zeros - initallizes with value zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# using rand
torch.manual_seed(42)
torch.rand(2,3)
# manual_seed = random_contrrol

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [20]:
# using tensor
# for custom
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
# linspace- linear space
torch.linspace(0,1,10)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])