<a href="https://colab.research.google.com/github/un1u3/ml-labs/blob/main/Deep%20Learning/Pytorch/00_BasicsPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


#Core Pytorch Modules
| Module             | Purpose                               |
| ------------------ | ------------------------------------- |
| `torch`            | Tensors, math ops, core engine        |
| `torch.nn`         | Layers, models, activations, losses   |
| `torch.optim`      | Optimizers (SGD, Adam, etc.)          |
| `torch.utils.data` | Datasets and DataLoaders              |
| `torch.autograd`   | Automatic gradient computation        |
| `torchvision`      | Images, pretrained models, transforms |


What are Tensors
- Tensor is a specialied multi-dimensional arra designed for mathematical and computational efficiency

In [ ]:
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("CUA",torch.cuda.get_device_name(0))
else:
  print("NO")

CUA Tesla T4


# creating a tensor


In [ ]:
# using empty
a = torch.empty(2,3)
# make space for 2x3 mat

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros - initallizes with value zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.manual_seed(42)
torch.rand(2,3)
# manual_seed = random_contrrol

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# using tensor
# for custom
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# linspace- linear space
torch.linspace(0,1,10)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

# Tensor Shapes

In [22]:
x = torch.tensor([[1,1,1,1],[2,3,4,5,]])

In [23]:
x.shape

torch.Size([2, 4])

In [26]:
torch.empty_like(x)
# copies the shape of tensor

tensor([[    133924732722576,     133924732722576,                   0,
                           0],
        [                  0, 7310593858020254331, 3616445622929465956,
         6066403867848879413]])

In [27]:
torch.zeros_like(x)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])

# Tensor data types

In [28]:
# find data type
x.dtype

torch.int64

In [33]:
# assign datatype
torch.tensor([1.0,2.0,3.1],dtype=torch.int)

tensor([1, 2, 3], dtype=torch.int32)

In [36]:
torch.tensor([1.0,2.0,3.1],dtype=torch.float32)

tensor([1.0000, 2.0000, 3.1000])

# mathematical operations in tensor

1. Scalar operations

In [40]:
x = torch.tensor([[1,2,3],[3,2,1]])
y = torch.tensor([[2,2,2],[2,2,2]])

In [42]:
# addition
x + y
# sub
x - y
# multiplication
x * y
# division
x / y
# mod
x % y


tensor([[1, 0, 1],
        [1, 0, 1]])

In [47]:
c = torch.tensor([1,2,3])

In [48]:
# absolute vlaue
torch.abs(c)

tensor([1, 2, 3])

In [49]:
# negative
torch.neg(c)

tensor([-1, -2, -3])

In [59]:
 # Reduction Operation
e = torch.randint(size=(2,3),low=0,high=10)
e

tensor([[9, 3, 1],
        [9, 7, 9]])

In [60]:
# mean
torch.mean(a)

tensor(4.6075e-41)

In [66]:
# standard deviatioon
torch.std(a)

tensor(1.1282e-40)

# Inplace Operations


In [71]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)
m.add_(n)

tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447]])
tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])


tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])

In [72]:
torch.relu_(m)

tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])

In [74]:
# Copyina a tensor
a = torch.rand(2,3)
a

tensor([[0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025]])

In [86]:
b = a.clone()

In [89]:
id(b)

133919645398608