<a href="https://colab.research.google.com/github/un1u3/ml-labs/blob/main/Deep%20Learning/Pytorch/03_NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



What is NN Module

torch.nn stands for Neural Network module — it provides:

- Pre-built layers (e.g., Linear, Conv2d, LSTM, etc.)

- Activation functions (e.g., ReLU, Sigmoid)

- Loss functions (e.g., CrossEntropyLoss, MSELoss)

- Model definition base class (nn.Module)

- Containers like Sequential to group layers

In [1]:
# create a model class

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    put = self.sigmoid(out)
    return out

In [2]:
# create dataser
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])
model.forward(features)

tensor([[ 0.0337],
        [-0.0226],
        [ 0.0163],
        [ 0.1546],
        [-0.2373],
        [ 0.2096],
        [ 0.2151],
        [ 0.4086],
        [ 0.3276],
        [ 0.1284]], grad_fn=<AddmmBackward0>)

In [3]:
# show the model weights

model.linear.weight

Parameter containing:
tensor([[-0.4122, -0.1745, -0.2501,  0.4296, -0.1230]], requires_grad=True)

In [4]:
# visualize
from torchinfo import summary
summary(model,input_size=(10,5))

ModuleNotFoundError: No module named 'torchinfo'

In [ ]:
# create a model class

import torch
import torch.nn as nn

class Model1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()
    self.relu = nn.ReLU()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [ ]:
# create dataser
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])
model.forward(features)

In [ ]:
# visualize
from torchinfo import summary

# create an instance of Model1
model1_instance = Model1(num_features=5) # Assuming num_features is 5 based on previous code

summary(model1_instance,input_size=(10,5))

In [ ]:
# create a model class by simpilfying the model

import torch
import torch.nn as nn

class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [ ]:
# visualize
from torchinfo import summary

# create an instance of Model1
model2_instance = Model2(num_features=5) # Assuming num_features is 5 based on previous code

summary(model2_instance,input_size=(10,5))

In [9]:
#  nn.Linear: Fully Connected Layer
# Purpose: Applies a linear transformation: y = xW^T + b
# Common Use: Used in feedforward networks for dense connections between layers.
# Define a linear layer with input size 3 and output size 2
linear = nn.Linear(3, 2)
# Example input
x = torch.tensor([[1.0, 2.0, 3.0]])
output = linear(x)
print("Output:", output)

Output: tensor([[-2.5950,  0.3397]], grad_fn=<AddmmBackward0>)


In [10]:
#  nn.Conv2d: Convolutional Layer
# Purpose: Performs 2D convolution for image data.
# Common Use: Extracts spatial features in computer vision tasks.
# Parameters:
# in_channels: Number of input channels (e.g., RGB has 3 channels).
# out_channels: Number of output channels (filters).
# kernel_size: Size of the convolutional kernel.
conv = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3)
# Example input (batch of 1, 3 channels, 32x32 image)
x = torch.randn(1, 3, 32, 32)
output = conv(x)
print("Output shape:", output.shape)  # Shape: (1, 6, 30, 30)


Output shape: torch.Size([1, 6, 30, 30])


In [13]:
# . nn.ReLU: Activation Function
# Purpose: Applies the ReLU function: ReLU(x)=max⁡(0,x)
# Common Use: Adds non-linearity after linear or convolutional layers.


relu = nn.ReLU()
x = torch.randn(1, 3, 32, 32)
output = relu(x)
output

tensor([[[[0.0000, 0.2163, 1.9069,  ..., 0.0000, 0.0000, 0.1688],
          [0.4885, 0.0000, 0.0000,  ..., 0.0000, 0.6127, 1.6627],
          [0.4599, 1.4968, 0.0467,  ..., 0.3936, 0.0000, 1.2783],
          ...,
          [0.0000, 2.0083, 1.4023,  ..., 0.0143, 0.0000, 0.5679],
          [1.5655, 0.3150, 0.0000,  ..., 0.8891, 0.4494, 0.0000],
          [0.0000, 1.6908, 0.0000,  ..., 0.3408, 0.2702, 1.4028]],

         [[0.0000, 0.0000, 0.0000,  ..., 0.8529, 0.9163, 1.2107],
          [0.0000, 0.9762, 1.7560,  ..., 1.0580, 1.1093, 0.4588],
          [1.4134, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.3275,  ..., 0.1718, 0.0000, 2.6092],
          [0.0926, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.2389, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.5183, 0.0000, 0.1508,  ..., 0.0000, 0.3746, 0.0000],
          [0.0000, 0.0965, 0.3171,  ..., 0.0000, 0.0000, 0.3842],
          [1.3842, 0.2625, 0.6234,  ..., 0