<a href="https://colab.research.google.com/github/un1u3/ml-labs/blob/main/Deep%20Learning/Pytorch/03_NN_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



What is NN Module

torch.nn stands for Neural Network module — it provides:

- Pre-built layers (e.g., Linear, Conv2d, LSTM, etc.)

- Activation functions (e.g., ReLU, Sigmoid)

- Loss functions (e.g., CrossEntropyLoss, MSELoss)

- Model definition base class (nn.Module)

- Containers like Sequential to group layers

In [5]:
# create a model class

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    put = self.sigmoid(out)
    return out

In [6]:
# create dataser
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])
model.forward(features)

tensor([[0.3833],
        [0.5139],
        [0.5910],
        [0.4864],
        [0.3993],
        [0.1755],
        [0.7081],
        [0.7471],
        [0.5705],
        [0.2877]], grad_fn=<AddmmBackward0>)

In [9]:
# show the model weights

model.linear.weight

Parameter containing:
tensor([[-0.3225, -0.0378,  0.1541,  0.2058,  0.3325]], requires_grad=True)

In [12]:
# visualize
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [19]:
# create a model class

import torch
import torch.nn as nn

class Model1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()
    self.relu = nn.ReLU()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [15]:
# create dataser
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])
model.forward(features)

tensor([[-0.0180],
        [ 0.0672],
        [-0.0099],
        [ 0.2776],
        [ 0.2746],
        [ 0.1768],
        [ 0.1793],
        [ 0.2898],
        [ 0.1866],
        [ 0.0615]], grad_fn=<AddmmBackward0>)

In [21]:
# visualize
from torchinfo import summary

# create an instance of Model1
model1_instance = Model1(num_features=5) # Assuming num_features is 5 based on previous code

summary(model1_instance,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [27]:
# create a model class by simpilfying the model

import torch
import torch.nn as nn

class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [28]:
# visualize
from torchinfo import summary

# create an instance of Model1
model2_instance = Model2(num_features=5) # Assuming num_features is 5 based on previous code

summary(model2_instance,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00