<a href="https://colab.research.google.com/github/un1u3/ml-labs/blob/main/Deep%20Learning/Pytorch/05_Dataset_%26_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
from sklearn.datasets import make_classification
import torch

In [89]:
X, y = make_classification(
    n_samples =10,
    n_features= 10,
    n_informative=2,
    n_redundant= 0,
    n_classes= 2,
    random_state=42
)

In [90]:
X

array([[-0.70205309, -1.46351495,  1.97686236, -0.39210815, -0.5297602 ,
         0.96864499, -2.8953973 ,  0.51326743,  0.09707755, -0.32766215],
       [-1.47852199,  1.05712223, -1.97171753, -0.46063877,  0.73846658,
        -0.3011037 , -0.58723065,  0.17136828, -0.11564828, -0.71984421],
       [ 0.36163603,  1.53803657, -0.97007347,  0.36139561,  0.81252582,
         1.0035329 ,  1.06833894,  1.35624003, -0.07201012, -0.64511975],
       [ 0.2088636 ,  0.19686124, -0.96059253, -1.32818605, -0.01349722,
        -1.22084365, -0.72063436, -1.05771093,  0.82254491, -1.95967012],
       [ 0.25755039, -0.02651388,  0.83444483, -1.91877122, -0.16128571,
         0.17457781,  1.89969252,  0.40405086,  1.8861859 , -0.07444592],
       [-0.676922  ,  0.93128012, -0.83879234,  1.03099952,  0.34361829,
        -0.38508228, -1.14021544, -1.76304016,  0.32408397,  0.61167629],
       [-1.41537074, -0.80227727,  1.51157598, -0.34271452,  0.29612028,
        -0.23458713,  1.77736657,  0.26105527

In [91]:
X.shape

(10, 10)

In [92]:
y.shape

(10,)

In [93]:
X = torch.tensor(X,dtype=float)

In [94]:
y = torch.tensor(y,dtype=float)

In [95]:
X

tensor([[-0.7021, -1.4635,  1.9769, -0.3921, -0.5298,  0.9686, -2.8954,  0.5133,
          0.0971, -0.3277],
        [-1.4785,  1.0571, -1.9717, -0.4606,  0.7385, -0.3011, -0.5872,  0.1714,
         -0.1156, -0.7198],
        [ 0.3616,  1.5380, -0.9701,  0.3614,  0.8125,  1.0035,  1.0683,  1.3562,
         -0.0720, -0.6451],
        [ 0.2089,  0.1969, -0.9606, -1.3282, -0.0135, -1.2208, -0.7206, -1.0577,
          0.8225, -1.9597],
        [ 0.2576, -0.0265,  0.8344, -1.9188, -0.1613,  0.1746,  1.8997,  0.4041,
          1.8862, -0.0744],
        [-0.6769,  0.9313, -0.8388,  1.0310,  0.3436, -0.3851, -1.1402, -1.7630,
          0.3241,  0.6117],
        [-1.4154, -0.8023,  1.5116, -0.3427,  0.2961, -0.2346,  1.7774,  0.2611,
          0.0051, -0.4206],
        [-0.4792, -1.1962, -0.5430, -1.1063, -0.8392,  0.9755, -0.9382, -0.3092,
          0.3313, -0.1857],
        [-0.8085,  0.3288, -0.9923,  0.9154, -0.2197, -0.5183, -1.9629,  0.3571,
          1.4779, -0.5018],
        [ 0.0870, -

In [96]:
from torch.utils.data import Dataset, DataLoader

In [97]:
class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [98]:
dataset = CustomDataset(X,y)

In [99]:
dataset[2]

(tensor([ 0.3616,  1.5380, -0.9701,  0.3614,  0.8125,  1.0035,  1.0683,  1.3562,
         -0.0720, -0.6451], dtype=torch.float64),
 tensor(1., dtype=torch.float64))

In [100]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [101]:
for features, labels in dataloader:
  print(features.shape, labels.shape)

torch.Size([2, 10]) torch.Size([2])
torch.Size([2, 10]) torch.Size([2])
torch.Size([2, 10]) torch.Size([2])
torch.Size([2, 10]) torch.Size([2])
torch.Size([2, 10]) torch.Size([2])


PyTorch’s DataLoader automatically shuffles the data and provide batches in a random order during training, which helps prevent the model from memorizing the order of the training samples

In [102]:
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from torchmetrics import Accuracy


In [103]:
from sklearn.datasets import load_diabetes

In [104]:
data = load_diabetes()

In [105]:
class Diabeties_dataset(Dataset):

  def __init__(self):
    super(Diabeties_dataset,self).__init__()
    data = load_diabetes() # Load data inside init
    self.x = torch.from_numpy(data.data) # Access the data using .data attribute
    self.y = torch.from_numpy(data.target).reshape(-1, 1) # Access target using .target attribute and reshape
    self.scaler = StandardScaler()
    # Scale x after converting to numpy and back to torch
    self.x = torch.from_numpy(self.scaler.fit_transform(self.x.numpy()))
    self.n_samples = len(data.data) # Use len of data.data for n_samples

  def __getitem__(self, index):
    return self.x[index].float(), self.y[index].float() # Ensure both are float

  def __len__(self):
    return self.n_samples

In [106]:
dataset = Diabeties_dataset()
dataloader = DataLoader(dataset=dataset, batch_size=2, shuffle=True)

In [107]:
for data in dataloader:
    features , label = data
    print('features', features)
    print('label', label)
    break
# as you see above when the batch size is 2 it gives us two samples of dataset


features tensor([[-0.8796, -0.9385, -1.3994, -0.9878, -0.7851, -0.9098,  1.0226, -0.8303,
         -1.1806, -0.2839],
        [-0.6505,  1.0655,  0.0281, -0.1192,  1.3555,  1.0389, -0.9899,  2.2729,
          1.7618,  0.0644]])
label tensor([[ 59.],
        [229.]])


In [114]:
# hyper parameters
# Hyperparameters
batch_size = 16
input_size = 10 # Corrected input_size to match the number of features in the dataset
n_dim = 64
lr = 0.001
epochs = 10

# Model
model = nn.Sequential(
    nn.Linear(input_size, n_dim*2),
    nn.ReLU(),
    nn.Linear(n_dim*2, n_dim),
    nn.ReLU(),
    nn.Linear(n_dim, 1),
    # Removed Sigmoid for regression task
)

# Accuracy metric (removed as it's for classification)
# accuracy = Accuracy(task='binary')

# Optimizer and Loss function
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
criterion = torch.nn.MSELoss() # Changed loss function to MSELoss for regression

In [116]:
for epoch in range(epochs):
    losses = []
    # accuracies = [] # Removed accuracy list

    # iterating over the dataset
    for features, labels in dataloader:

        # setting grads to zero
        optimizer.zero_grad()

        # forward prop
        logits = model(features)
        loss = criterion(logits, labels)

        # backprop
        loss.backward()
        optimizer.step()

        losses.append(loss.item())
        # accuracies.append(accuracy(logits, labels).item()) # Removed accuracy calculation

    # calculating mean loss through the epoch
    mean_loss = np.mean(losses)
    # mean_accuracy = np.mean(accuracies) # Removed accuracy calculation
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {mean_loss:.4f}") # Modified print statement

Epoch [1/10], Loss: 17757.8807
Epoch [2/10], Loss: 3948.0834
Epoch [3/10], Loss: 3276.0960
Epoch [4/10], Loss: 3068.9113
Epoch [5/10], Loss: 2962.9496
Epoch [6/10], Loss: 2882.0385
Epoch [7/10], Loss: 2831.3880
Epoch [8/10], Loss: 2794.0444
Epoch [9/10], Loss: 2789.5931
Epoch [10/10], Loss: 2748.5153
