<a href="https://colab.research.google.com/github/un1u3/ml-labs/blob/main/Deep%20Learning/Pytorch/5_Tensor%26Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
# creating a tensor
x = torch.tensor([1,2,3,4,5])
print(x)

# 2d tensors
y = torch.tensor([[1,2,3],
                  [4,5,6]])
print(y)

# creating tensors with zeros
z = torch.zeros([3,3])
print(z)

# with random
a = torch.randn(6,7)
print(a)

# with ones
torch.ones(2,3)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.8207, -0.4636,  2.2914, -1.0019, -0.9674, -0.4785,  0.1875],
        [ 0.3479, -1.4498, -1.4612, -0.8216,  1.2872,  0.8449,  0.4651],
        [-1.6367, -0.0495,  0.7198, -0.6639,  1.0570, -0.6722,  1.1626],
        [-1.1501,  1.2027, -0.9899,  0.3303, -0.6347,  0.8344,  0.3473],
        [-0.3300,  0.4039, -1.9422, -0.9397,  1.4549,  0.6852, -1.0334],
        [-1.3551,  0.7238, -1.4574, -0.9819, -1.4929, -0.4152, -1.5604]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# tensor operations
x = torch.randn(2,3,4)
print("Original Shape",x.shape)

y = x.reshape(6,4)
print("ReShape",y.shape)

z  = y.view(-1)
print("Flatten",z.shape)


Original Shape torch.Size([2, 3, 4])
ReShape torch.Size([6, 4])
Flatten torch.Size([24])


In [ ]:
#  Common operations
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("\nAddition:", a + b)
print("Multiplication:", a * b)  # element-wise
print("Mean:", a.mean())
print("Sum:", a.sum())



Addition: tensor([5., 7., 9.])
Multiplication: tensor([ 4., 10., 18.])
Mean: tensor(2.)
Sum: tensor(6.)


In [ ]:
# Matrix multiplication (dot product)
A = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])  # 3x2

B = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])  # 2x3


C = torch.matmul(A,B)
print("Matrix mul", C)


D = A @ B
print("Matrix mul", D)



Matrix mul tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Matrix mul tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [ ]:
# autograd

x = torch.tensor(4.0,requires_grad = True)
x

tensor(4., requires_grad=True)

In [ ]:
y = x ** 2

In [ ]:
y.backward()

In [ ]:
print("dy/dx",x.grad)

dy/dx tensor(8.)


In [ ]:
# more complex differentatio
x = torch.tensor(20.0,requires_grad=True)
y = x ** 2 + x + x ** 2
y.backward()
x.grad

In [ ]:
# Simple Neural Net Module

class SimpleNN(nn.Module):
  def __init__(self):
    super().__init__()
    # define layer
    self.layer = nn.Linear(5,3) # 5 inputs/ 3 o/p

  def forward(self,x):
    return self.layer(x)
model = SimpleNN()
print(model)

SimpleNN(
  (layer): Linear(in_features=5, out_features=3, bias=True)
)


In [ ]:
x = torch.randn(2, 5)  # Batch of 2, 5 features each
output = model(x)
print("\nInput shape:", x.shape)
print("Output shape:", output.shape)



Input shape: torch.Size([2, 5])
Output shape: torch.Size([2, 3])


In [ ]:
# Linear layer: y = Wx + b
linear = nn.Linear(in_features=10, out_features=5)
x = torch.randn(3, 10)  # Batch of 3
output = linear(x)
print("Linear layer output:", output.shape)  # torch.Size([3, 5])

# ReLU activation: max(0, x)
relu = nn.ReLU()
x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
output = relu(x)
print("\nReLU output:", output)  # tensor([0., 0., 0., 1., 2.])

# Combining them
x = torch.randn(2, 10)
x = linear(x)
print("Before ReLU:", x)
x = relu(x)
print("After ReLU:", x)  # All negative values → 0

Linear layer output: torch.Size([3, 5])

ReLU output: tensor([0., 0., 0., 1., 2.])
Before ReLU: tensor([[-0.2227,  0.2982,  1.8712,  0.5120, -0.2025],
        [-0.1586,  0.3866,  0.8604, -0.0081,  1.0745]],
       grad_fn=<AddmmBackward0>)
After ReLU: tensor([[0.0000, 0.2982, 1.8712, 0.5120, 0.0000],
        [0.0000, 0.3866, 0.8604, 0.0000, 1.0745]], grad_fn=<ReluBackward0>)


In [ ]:
class ThreeLayerNetwork(nn.Module):
  def __init__(self):
    super().__init__()

    # input layer
    self.layer1 = nn.Linear(10,20) # ip 10 .hidden 20
    self.relu1 = nn.ReLU()

    self.layer2 = nn.Linear(20,20)
    self.relu2 = nn.ReLU()

    self.layer3 = nn.Linear(20,1)


  def forward(self,x):
    x = self.layer1(x)
    x = self.relu1(x)

    x = self.layer2(x)
    x = self.relu2(x)

    return x

In [ ]:
model = ThreeLayerNetwork()
print(model)

# Count parameters
total_params = sum(p.numel() for p in model.parameters())
print(f"\nTotal parameters: {total_params}")

# Forward pass with random data
batch_size = 5
x = torch.randn(batch_size, 10)  # 5 samples, 10 features each
output = model(x)

print(f"\nInput shape: {x.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n{output}")

ThreeLayerNetwork(
  (layer1): Linear(in_features=10, out_features=20, bias=True)
  (relu1): ReLU()
  (layer2): Linear(in_features=20, out_features=20, bias=True)
  (relu2): ReLU()
  (layer3): Linear(in_features=20, out_features=1, bias=True)
)

Total parameters: 661

Input shape: torch.Size([5, 10])
Output shape: torch.Size([5, 20])
Output:
tensor([[0.0000, 0.0000, 0.0721, 0.0471, 0.0000, 0.0000, 0.1041, 0.0000, 0.1696,
         0.0000, 0.0000, 0.0000, 0.5111, 0.0026, 0.0898, 0.4870, 0.0395, 0.0000,
         0.0000, 0.2339],
        [0.0000, 0.0000, 0.0000, 0.3225, 0.0339, 0.0058, 0.4403, 0.0000, 0.1287,
         0.4515, 0.3088, 0.0917, 0.2431, 0.0000, 0.4427, 0.3799, 0.4206, 0.0000,
         0.4289, 0.0000],
        [0.3757, 0.0532, 0.0000, 0.3238, 0.0000, 0.0000, 0.0160, 0.0000, 0.4666,
         0.0000, 0.1649, 0.0000, 0.7694, 0.0000, 0.3853, 0.3345, 0.0296, 0.0000,
         0.3373, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0202, 0.0000, 0.0000, 0.2262, 0.0000, 0.1185,
         0.

In [ ]:
class CompactNetwork(nn.Module):
  def __init__(self):
    super().__init__()

    # input layer

    self.network = nn.Sequential(
    nn.Linear(10,20), # ip 10 .hidden 20
    nn.ReLU(),
    nn.Linear(20,20),
    nn.ReLU(),
    nn.Linear(20,1),
    )


  def forward(self,x):

    return self.network(x)

In [ ]:
model2 = CompactNetwork()
output2 = model2(torch.randn(5, 10))
print("Compact network output shape:", output2.shape)

Compact network output shape: torch.Size([5, 1])
