<a href="https://colab.research.google.com/github/un1u3/ml-labs/blob/main/Deep%20Learning/Pytorch/5_Tensor%26Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

In [ ]:
# creating a tensor
x = torch.tensor([1,2,3,4,5])
print(x)

# 2d tensors
y = torch.tensor([[1,2,3],
                  [4,5,6]])
print(y)

# creating tensors with zeros
z = torch.zeros([3,3])
print(z)

# with random
a = torch.randn(6,7)
print(a)

# with ones
torch.ones(2,3)

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.8207, -0.4636,  2.2914, -1.0019, -0.9674, -0.4785,  0.1875],
        [ 0.3479, -1.4498, -1.4612, -0.8216,  1.2872,  0.8449,  0.4651],
        [-1.6367, -0.0495,  0.7198, -0.6639,  1.0570, -0.6722,  1.1626],
        [-1.1501,  1.2027, -0.9899,  0.3303, -0.6347,  0.8344,  0.3473],
        [-0.3300,  0.4039, -1.9422, -0.9397,  1.4549,  0.6852, -1.0334],
        [-1.3551,  0.7238, -1.4574, -0.9819, -1.4929, -0.4152, -1.5604]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# tensor operations
x = torch.randn(2,3,4)
print("Original Shape",x.shape)

y = x.reshape(6,4)
print("ReShape",y.shape)

z  = y.view(-1)
print("Flatten",z.shape)


Original Shape torch.Size([2, 3, 4])
ReShape torch.Size([6, 4])
Flatten torch.Size([24])


In [ ]:
#  Common operations
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("\nAddition:", a + b)
print("Multiplication:", a * b)  # element-wise
print("Mean:", a.mean())
print("Sum:", a.sum())



Addition: tensor([5., 7., 9.])
Multiplication: tensor([ 4., 10., 18.])
Mean: tensor(2.)
Sum: tensor(6.)


In [ ]:
# Matrix multiplication (dot product)
A = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])  # 3x2

B = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])  # 2x3


C = torch.matmul(A,B)
print("Matrix mul", C)


D = A @ B
print("Matrix mul", D)



Matrix mul tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Matrix mul tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [3]:
# autograd

x = torch.tensor(4.0,requires_grad = True)
x

tensor(4., requires_grad=True)

In [6]:
y = x ** 2

In [8]:
y.backward()

In [10]:
print("dy/dx",x.grad)

dy/dx tensor(8.)


In [ ]:
# more complex differentatio
x = torch.tensor(20.0,requires_grad=True)
y = x ** 2 + x + x ** 2
y.backward()
x.grad