<a href="https://colab.research.google.com/github/un1u3/ml-labs/blob/main/Deep%20Learning/Pytorch/60_Min_Blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
# Tensors
# A tensor is a generalization of vector and matrices
# Scalar = 0-D tensor
# Vecotr = 1-D tendor
# Matrix = 2-D tensor
# high dimensional tensor = 3-D, 4D , nD
# tensors are similar to matrirces and NumPy's nDarray
# tensor can run in GPU

In [20]:
import torch
import numpy as np

In [21]:
# tensor initialization
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [22]:
# more on tensors
print(torch.rand(3,4))
print(torch.ones(3,2))
print(torch.zeros(3,4))

tensor([[0.4043, 0.4623, 0.3120, 0.5801],
        [0.2428, 0.7969, 0.7501, 0.4471],
        [0.8924, 0.5160, 0.8305, 0.3379]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [23]:
# tensor attribute
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)


torch.Size([3, 4])
torch.float32
cpu


In [29]:
# tensor operation
# 1. element wise operation
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
print( x + y )
print( x - y )
print( x * y )
print( x / y )




tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [32]:
# 2.matrix multiplication/Dot product
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[5,6],[7,8]])
torch.matmul(A,B)


tensor([[19, 22],
        [43, 50]])

In [40]:
# 3.Transpose
A.T
# 4.Reshape
x = torch.arange(6)
y = x.view(3,2)
y

tensor([[0, 1],
        [2, 3],
        [4, 5]])