In [4]:
from transformers import AutoTokenizer 


checkpoint = 'distilbert-base-uncased-finetuned-sst-2-english' #checkpoint means weights of model 
tokenizer = AutoTokenizer.from_pretrained(checkpoint) # it used weights of checkpoint model

raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")
print(inputs)


{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [6]:
from transformers import AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)

In [8]:
print(outputs.logits)

tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


In [9]:
import torch

predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)

tensor([[4.0195e-02, 9.5981e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


In [10]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [16]:
from transformers import AutoTokenizer
sentence = "I love tokens"
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
tokenizer.encode(sentence)


[101, 146, 1567, 22559, 1116, 102]

In [19]:
tokens = tokenizer.tokenize(sentence)
tokens

['I', 'love', 'token', '##s']

In [22]:
tokenizer.decode([101, 146, 1567, 22559, 1116, 102])

'[CLS] I love tokens [SEP]'

In [24]:
tokenizer.convert_tokens_to_ids(tokens)

[146, 1567, 22559, 1116]

In [39]:
import torch 
from transformers import AutoTokenizer, AutoModelForSequenceClassification


checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "I am here coding a transformer"


tokens = tokenizer.tokenize(sequence)
print(tokens)

ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

input_ids = torch.tensor([ids])
print(input_ids)

outputs = model(input_ids)
outputs

torch.nn.functional.softmax(outputs.logits,dim=-1)

['i', 'am', 'here', 'coding', 'a', 'transform', '##er']
[1045, 2572, 2182, 16861, 1037, 10938, 2121]
tensor([[ 1045,  2572,  2182, 16861,  1037, 10938,  2121]])


tensor([[0.9980, 0.0020]], grad_fn=<SoftmaxBackward0>)

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequences = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]

tokens = tokenizer(sequences, padding=True, truncation=True, return_tensors="pt")
output = model(**tokens)
output

SequenceClassifierOutput(loss=None, logits=tensor([[-1.5607,  1.6123],
        [-3.6183,  3.9137]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)