In [3]:
import numpy as np

class Perceptron(object):

    def __init__(self, eta=0.01, n_iter=10):
        self.eta = eta
        self.n_iter = n_iter
    def weighted_sum(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]
    def predict(self, X):
        return np.where(self.weighted_sum(X) >= 0.0, 1, -1)
    def fit(self, X, y):

        # initializing the weights to 0
        self.w_ = np.zeros(1 + X.shape[1])
        self.errors_ = []

        print("Weights:", self.w_)

        # training the model n_iter times
        for _ in range(self.n_iter):
            error = 0

            # loop through each input
            for xi, y in zip(X, y):

                # 1. calculate ŷ (the predicted value)
                y_pred = self.predict(xi)

                # 2. calculate Update
                # update = η * (y - ŷ)
                update = self.eta * (y - y_pred)

                # 3. Update the weights
                # Wi = Wi + Δ(Wi)   where  Δ(Wi) = η * (y - ŷ) = update * Xi
                self.w_[1:] = self.w_[1:] + update * xi
                print("Updated Weights:", self.w_[1:])

                # Update the bias (Xo = 1)
                self.w_[0] = self.w_[0] + update

                # if update != 0, it means that ŷ != y
                error += int(update != 0.0)

            self.errors_.append(error)

        return self

In [4]:
import pandas as pd
from sklearn.utils import shuffle
import numpy as np

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
# Shuffling the data
df = shuffle(df)

df.head()

,0,1,2,3,4
51,6.4,3.2,4.5,1.5,Iris-versicolor
100,6.3,3.3,6.0,2.5,Iris-virginica
38,4.4,3.0,1.3,0.2,Iris-setosa
46,5.1,3.8,1.6,0.2,Iris-setosa
92,5.8,2.6,4.0,1.2,Iris-versicolor


In [5]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values

print(X[0:5])
print(y[0:5])

[[6.4 3.2 4.5 1.5]
 [6.3 3.3 6.  2.5]
 [4.4 3.  1.3 0.2]
 [5.1 3.8 1.6 0.2]
 [5.8 2.6 4.  1.2]]
['Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor']


In [7]:
from sklearn.model_selection import train_test_split
train_data, test_data, train_labels, test_labels = train_test_split(
                            X, y, test_size=0.20)

# Encoding the labels: 1 for setosa, -1 otherwise
train_labels = np.where(train_labels == 'Iris-setosa', 1, -1)
test_labels = np.where(test_labels == 'Iris-setosa', 1, -1)

print('Train data:', train_data[0:2])
print('Train labels:', train_labels[0:5])

print('Test data:', test_data[0:2])
print('Test labels:', test_labels[0:5])

Train data: [[5.1 3.5 1.4 0.2]
 [6.5 3.  5.8 2.2]]
Train labels: [ 1 -1  1 -1 -1]
Test data: [[4.9 2.5 4.5 1.7]
 [5.6 3.  4.5 1.5]]
Test labels: [-1 -1 -1 -1 -1]


In [15]:

perceptron = Perceptron(eta=0.1, n_iter=10)
perceptron.fit(train_data, train_labels)

Weights: [0. 0. 0. 0. 0.]
Updated Weights: [0. 0. 0. 0.]
Updated Weights: [-1.3  -0.6  -1.16 -0.44]
Updated Weights: [-0.28  0.16 -0.78 -0.36]
Updated Weights: [-0.28  0.16 -0.78 -0.36]
Updated Weights: [-0.28  0.16 -0.78 -0.36]
Updated Weights: [-0.28  0.16 -0.78 -0.36]
Updated Weights: [ 0.58  0.76 -0.56 -0.34]
Updated Weights: [-0.64  0.2  -1.5  -0.58]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.54]
Updated Weights: [ 0.24  0.8  -1.24 -0.5

TypeError: 'numpy.int64' object is not iterable

In [16]:
test_preds = perceptron.predict(test_data)
print(test_preds)


[-1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1  1 -1 -1 -1  1  1 -1
  1 -1 -1 -1 -1 -1]


In [19]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_preds, test_labels)
print('Accuracy:', round(accuracy, 2) * 100, "%")


NameError: name 'y_preds' is not defined